### ISSUE TITLE
Unable to originate new floating rate bond

### ISSUE THREAD

**Issue by ianw-da** [digital-asset/daml-finance-app#27]
Default scenario, issuer login, structuring, latest code (post 13 Sept changes). Try to create new floating rate bond, nothing happens when pressing "create instrument". Following error in JavaScript console:
"DAML_INTERPRETER_INVALID_ARGUMENT(8,2c11afb6): Interpretation error: Error: Update failed due to wrongly typed contract id 00daaa0e4a31dc650602c12027043467ce85251e2fd6a3d1c6204df8daa2ee2f46ca0012205713a0b33b0e7ae7e9cd611644ef69a12506b5dc4ffad6dd06c8db94ee8dd356
Expected contract of type Daml.Finance.App.Structuring.Auto.Service:Service@afbe6a7f but got Daml.Finance.App.Structuring.Service:Service@afbe6a7f"

**Comment by GeorgSchneider** [comment]
Fixed via https://github.com/digital-asset/daml-finance-app/pull/28
