### ISSUE TITLE
Claims tree not displayed when viewing Tesla Forward

### ISSUE THREAD

**Issue by ianw-da** [digital-asset/daml-finance-app#40]
Log in as Issuer, go to structuring, details, for FWD-TSLA-USD-20221022.

The claims tree just shows one "zero" box.

BOND-USD-5Y-4.875% works correctly.

This is on #37.

**Comment by GeorgSchneider** [comment]
Should be fixed with https://github.com/digital-asset/daml-finance-app/pull/41 - pls confirm
